### PR TITLE
Install devbio napari on an arm64 mac

### PR DESCRIPTION
**Pull request by thawn**
Since Robert Muench asked for help with installing `devbio-napari` on an arm64 mac, I thought I write down my way to get this to work as a blog article.

@haesleinhuepf did you maybe find an easier way?

The way I describe allows to have both the arm64 and the i386 versions in parallel, which makes it a bit complicated - but allows to run python code that works on arm64 natively.

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
Thanks @thawn for this blog post! Before merging it I'd like to wait for the potential fixes here:
* https://github.com/haesleinhuepf/devbio-napari/issues/23

**Comment by psobolewskiPhD** [comment]
Bah, something in devbio-napari has PyQt5 as a hard depend rather than `qtpy` so you can't easily work around the lack of pyqt5 for arm64 on pip by installing pyqt from conda-forge. What a bummer.

**Comment by psobolewskiPhD** [comment]
I've found the PyQt culprit: it's PlatyMatch. I will see if I can make a PR there to fix it, just sanity checking on zulip that I understand things correctly.

**Comment by psobolewskiPhD** [comment]
PR made:
https://github.com/juglab/PlatyMatch/pull/7
This should make PlatyMatch pip installable on arm64 M1.

**Comment by thawn** [comment]
@psobolewskiPhD kudos for the PlayMatch PR :-)

**Comment by thawn** [comment]
> wait for the potential fixes here: https://github.com/haesleinhuepf/devbio-napari/issues/23

I am a bit worried, that the simpleitk migration to arm64 might not come in time for our course. Also, the rosetta installation requires sudo, which means that some students that do not have admin rights will need assistance from the IT department. Therefore, I would like to give the students with an arm64 system the chance to install devbio-napari with help from the IT in the week before the course.

I am perfectly fine with sending them the link to this branch, without merging the article. However, I was wondering if @haesleinhuepf found an installation method that is a bit simpler (i.e. not requiring manual edits of `.zsh_profile`)

**Comment by psobolewskiPhD** [comment]
Also pure conda install should be working soon too!
I *think* this is the only holdup: https://github.com/conda-forge/simpleitk-feedstock/pull/27#pullrequestreview-1128790505

**Comment by thawn** [comment]
obsolete because native arm64 installation works now

**Pull request closed without merging**
