### PR TITLE
Omero scripts

### PR DESCRIPTION
**Pull request by zoccoler**
Hi Robert @haesleinhuepf , hi Johannes @jo-mueller ,

As previously discussed, I wrote this blog post to explain how to run an DL omero script, in this case a stardist 2D pretrained model. Could you please review it?

I wrote as if a broad audience could read this. Let me know if I should cut off the beginning for example.

Also, Robert @haesleinhuepf, it makes sense to add brief description of our server, doesn't it? I left some bold text to be edited.

Best,
Marcelo

### CODE REVIEW

**Comment by jo-mueller** [comment]
Hi @zoccoler ,

I get an error when I try to log onto the omero server with the client I installed:

Capture

According to [this issue ](https://forum.image.sc/t/omero-insight-login-issue/27644) on image.sc, this could be due to missmatching Omero version on the server/client side - do you knwo which Omero version is running on the server?

**Comment by zoccoler** [comment]
Hi Johannes,

That's unfortunate. Here are the versions from Client and Server. Try using Insight 5.6.2.
```
Server version: 5.6.3
Client version: 5.6.2
os_version: 10.0
java_version: 1.8.0_275
os_arch: amd64
os_name: Windows 10
```

Best,
Marcelo

**Comment by jo-mueller** [comment]
Strange - I'm receiving the same error for 5.6.2:
Capture

I do have it configured correctly, right?
Capture2

**Comment by zoccoler** [comment]
My bad, with Omero Insight, the address is slightly different. I fixed the text.
Use this one : omero-int.biotec.tu-dresden.de

**Comment by jo-mueller** [comment]
>Use this one : omero-int.biotec.tu-dresden.de

This worked, thanks!

**Comment by jo-mueller** [comment]
Also: All of the tutorial worked for me 💯 

Maybe a small suggestion: Could you add a brief section on how to import data to the server space? When I logged on, I first had to upload some data to be processed by the scripts.

**Comment by haesleinhuepf** [comment]
I think it would make sense to document the usage of the omero server via the browser. I think that's the default use-case. Only a minority of users will have the client installed. Would that be possible Marcelo @zoccoler ?

**Comment by zoccoler** [comment]
> Could you add a brief section on how to import data to the server space?

@jo-mueller , I don't fully understand this, I pointed a link to the tutorial from omero where they show how to import data. I think it is well described there and I didn't want to replicate that part. Is that what you mean or something else?

@haesleinhuepf , it makes sense, I will replace the "running scripts" part by a web interface fashion, but I think you need either the application or the command line to import data. The options are presented here: https://omero-guides.readthedocs.io/en/latest/upload/docs/import.html

**Comment by zoccoler** [comment]
I changed to the web version, but import data is still done with Omero Insight and left as an external tutorial.

**Comment by zoccoler** [comment]
Talking to @jo-mueller Johannes today, it looked like a good idea to briefly enumerate first the possible ways to access the server, making it clear why we need the application at least to import data. 

So I added a new section right in the beginning. 

It looks good to me! What do you guys think?

**Comment by haesleinhuepf** [comment]
Awesome, thanks Marcelo @zoccoler !

**Pull request merged**
