### PR TITLE
Embed GUIs into napari blog entry

### PR DESCRIPTION
**Pull request by zoccoler**
I have written the third part to embed GUIs into napari using 3 different approaches.
Let me know if you know improvements for them, if any of them is unnecessary or even if you know another useful one.

Please also let me know if you think the 'climate changes' trivia can be considered somehow inappropriate here.
I am not defending any cause, I just always played with flooding my images to check background homogeneity, so I did like that for fun 😄 

I had to let the part of turning these into plugins for a forth part because this was already too long for that.

P.S. sorry for the typo in the branch name xD

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
Hi Marcelo @zoccoler ,

can you please check if all changes were pushed to github? Your branch appears empty:
image

Best,
Robert

**Comment by zoccoler** [comment]
You are right, that's odd, let me check

**Comment by zoccoler** [comment]
Oh well, it seems I had merged it already... (my mistake)
I thought I was merging it locally before to get the latest updates.
Let me try to revert this.

**Comment by haesleinhuepf** [comment]
> Let me try to revert this.

image

Sometimes, it's tricky. It would also be completely fine if one of us sends a PR with suggestions to your blog post and you review and merge them.

The post looks great btw! <3

**Comment by zoccoler** [comment]
Am I reverting my changes now?

**Comment by zoccoler** [comment]
It seems, by the file changes, it is reverting things back. I am going to merge and then try a new PR with the new post.

**Comment by haesleinhuepf** [comment]
No hurry 🙂

**Pull request merged**
