### PR TITLE
Convert the blog to a Jupyter Book

### LINKED ISSUE #43: Convert blog to jupyter book
Hi all,

I recently started using jupyter books in another project. It makes it easy to manage collections of articles, markdown files and jupyter notebooks such as this blog. We could also use it here.

https://jupyterbook.org/start/overview.html

Do you have opinions?
@Cryaaa 
@jo-mueller 
@lazigu 
@zoccoler 

Thanks!
Robert

### PR DESCRIPTION
**Pull request by lazigu**
Hi all,

Here comes the PR that reorganizes the blog into a jupyter book.
I have also fixed a few typos, fixed some broken links to images, and changed quite a few links to relative ones instead of absolute ones for easier maintenance.

Please feel free to add changes to the intro page or organization of ToC if you wish.

The preview is available at https://lazigu.github.io/blog/

This PR closes #43

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
Wow @lazigu ! This looks amazing! 

One idea: I would put the recent 3-5 blog posts on the starting page...

Also you should write a blog post (about setting up a jupyter book? ;-) ) so that we can list you under authors :-)

**Comment by lazigu** [comment]
I added 5 of the most recent blog posts and fixed displayed images. I think this is finished now :)

**Comment by jo-mueller** [comment]
Looks super cool! I was wondering whether it would make sense to sort the posts according to topic or somehow add tags to it (similar how you can set topics in image.sc) but I think that's currently not possible. So - thumbs up from me :)

**Comment by lazigu** [comment]
We had a discussion during lunch about the organization of posts according to the topic. However, since we do not have that many blog posts yet, many topics might have just a couple of blog posts in them and we would lose chronological order. What do you @haesleinhuepf think?

**Comment by haesleinhuepf** [comment]
Yes, I agree. We definitely need more blog posts.

Ready? Shall we merge this? 🙃

**Comment by lazigu** [comment]
From my side yes :)
We can come back to the tags and better posts organization idea when the blog expands :)

**Pull request merged**
